// <auto-generated />
namespace My_Project_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Safikul : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Safikul));
        
        string IMigrationMetadata.Id
        {
            get { return "202406180425287_Safikul"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
